---
title: "multigroup-2spa-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{multigroup-2spa-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(tidyverse)
library(lavaan)
library(haven)
```


## Lui (2019)

The data is from ["College alcohol beliefs: Measurement invariance, mean differences, and correlations with alcohol use outcomes across sociodemographic groups" (Lui, 2019)](https://pubmed.ncbi.nlm.nih.gov/30777775/). 

```{r}
lui2018 <- read_sav("https://osf.io/wxjsg/download") %>%
  filter_at(vars(class14, audit1:audit3), ~ !is.na(.)) %>% 
  filter(eth %in% 1:4) %>%
  mutate_at(vars(class1:class15, audit1:audit10), as.numeric) %>%
  mutate(campuslive = factor(campuslive), 
         eth = factor(eth, 1:4)) %>%
  arrange(eth)
```


[WT]: # (Estimating fx and fy in the same model yields similar results as estimating them in two separate models, although a few parameter estiamtes differ slightly.)

[WT]: # (Fine if the local independence assumption holds for each factor. )

```{r}
# partial scalar model on X, and scalar model on Y
ps_mod <- "
fx =~ class1 + class2 + class3 + class4 + class5 + class6 + 
      class7 + class8 + class9 + class10 + class11 + class12 + 
      class13 + class14 + class15
fy =~ audit1 + audit2 + audit3

class1 ~ c(i1, i1, i1, i1.h)*1
class2 ~ c(i2, i2, i2, i2.h)*1
class4 ~ c(i4.w, i4, i4, i4)*1
class6 ~ c(i6, i6, i6.b, i6)*1
class10 ~ c(i10, i10.a, i10, i10)*1
class11 ~ c(i11, i11, i11, i11.h)*1
class12 ~ c(i12, i12.a, i12, i12)*1
class13 ~ c(i13, i13, i13.b, i13)*1
class14 ~ c(i14.w, i14, i14, i14)*1
class15 ~ c(i15, i15.a, i15, i15)*1
"
```

```{r}
psfit_eth <- cfa(model = ps_mod, 
                 data = lui2018, 
                 group = "eth", 
                 group.label = 1:4, 
                 group.equal = c("loadings", "intercepts"), 
                 std.lv = TRUE)
```

```{r}
# Put factor scores to data set
fs_lui <- cbind(do.call(rbind, lavPredict(psfit_eth, se = "standard")), 
                    rep(1:4, table(lui2018$eth)))
colnames(fs_lui) <- c("fs_fx", "fs_fy", "eth")
```


### Method 1: Constraints on the realibility

```{r}
# Reliability of factor scores (1 - fx_se^2 / fx_psi)
rel <- 1 - unlist(attributes(lavPredict(psfit_eth, se = "standard"))$se)^2 / 1
names(rel) <- paste0("rel_", rep(c("w", "a", "b", "h"), each = 2), c("_fx", "_fy"))
rel
```


```{r}
my2spa_lui <- '
   # latent variables (indicated by factor scores)
     fx =~ c(1, 1, 1, 1) * fs_fx
     fy =~ c(1, 1, 1, 1) * fs_fy
   # constrain the errors
     fs_fx ~~ c(ev11, ev12, ev13, ev14) * fs_fx
     fs_fy ~~ c(ev21, ev22, ev23, ev24) * fs_fy
   # latent variances
     fx ~~ c(v11, v12, v13, v14) * fx
     fy ~~ c(v21, v22, v23, v24) * fy
   # regressions
     fy ~ c(b1, b1, b1, b1) * fx
   # reliability constraints (reliability = v / (v + ev))
   # v = reliability / (1 - reliability) * ev
     v11 == (0.9280397 / (1 - 0.9280397)) * ev11
     v12 == (0.9241833 / (1 - 0.9241833)) * ev12
     v13 == (0.9122641 / (1 - 0.9122641)) * ev13
     v14 == (0.9172431 / (1 - 0.9172431)) * ev14
     v21 == (0.8854708 / (1 - 0.8854708)) * ev21 - b1^2 * v11
     v22 == (0.9389290 / (1 - 0.9389290)) * ev22 - b1^2 * v12
     v23 == (0.9108694 / (1 - 0.9108694)) * ev23 - b1^2 * v13
     v24 == (0.9120363 / (1 - 0.9120363)) * ev24 - b1^2 * v14
'
tspa_lui_fit <- sem(model = my2spa_lui,
                    data  = fs_lui, 
                    group = "eth", 
                    group.label = 1:4)
summary(tspa_lui_fit)
```

### Method 2: Constraints on the error variances

```{r}
# Error varainces
ev <- unlist(attributes(lavPredict(psfit_eth, se = "standard"))$se)^2
names(ev) <- paste0("ev_", rep(c("w", "a", "b", "h"), each = 2), c("_fx", "_fy"))
ev
```


```{r}
my2spa_lui <- '
   # latent variables (indicated by factor scores)
     fx =~ c(1, 1, 1, 1) * fs_fx
     fy =~ c(1, 1, 1, 1) * fs_fy
   # constrain the errors
     fs_fx ~~ c(0.07196033, 0.07581671, 0.08773593, 0.08275693) * fs_fx
     fs_fy ~~ c(0.11452919, 0.06107097, 0.08913058, 0.08796366) * fs_fy
   # latent variances
     fx ~~ c(v11, v12, v13, v14) * fx
     fy ~~ c(v21, v22, v23, v24) * fy
   # regressions
     fy ~ c(b1, b1, b1, b1) * fx
'
tspa_lui_fit <- sem(model = my2spa_lui,
                    data  = fs_lui, 
                    group = "eth", 
                    group.label = 1:4)
summary(tspa_lui_fit)
```

Most but not all estimates are comparable between methods. 

