---
title: "my-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(R2spa)
library(lavaan)
library(tidyverse)
library(haven)
```

The example is from https://lavaan.ugent.be/tutorial/sem.html. 

```{r}
myModel <- '
   # latent variables
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + y2 + y3 + y4
   # regressions
     dem60 ~ ind60
'
fit <- sem(model = myModel,
           data  = PoliticalDemocracy)
summary(fit)
semPlot::semPaths(fit)
standardizedSolution(fit)
```

# 2S-PA

```{r}
# CFA
my_cfa <- '
   # latent variables
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + y2 + y3 + y4
'
cfa_fit <- cfa(model = my_cfa,
               data  = PoliticalDemocracy)
semPlot::semPaths(cfa_fit)
# Compute factor scores using lavPredict
lavPredict(cfa_fit, se = "standard")
# reliability of factor scores
rel_ind60 <- 0.9651282
rel_dem60 <- 0.9055203
```

## Step 2

```{r}
# Put factor scores to data set
fs_dat <- lavPredict(cfa_fit, se = "standard")
colnames(fs_dat) <- c("fs_ind60", "fs_dem60")
my2spa <- '
   # latent variables (indicated by factor scores)
     ind60 =~ 1 * fs_ind60
     dem60 =~ 1 * fs_dem60
   # constrain the errors
     fs_ind60 ~~ ev1 * fs_ind60
     fs_dem60 ~~ ev2 * fs_dem60
   # latent variances
     ind60 ~~ v1 * ind60
     dem60 ~~ v2 * dem60
   # regressions
     dem60 ~ ind60
   # reliability constraints (reliability = v / (v + ev))
   # v = reliability / (1 - reliability) * ev
     v1 == 0.9651282 / (1 - 0.9651282) * ev1
     v2 == 0.9055203 / (1 - 0.9055203) * ev2
'
tspa_fit <- sem(model = my2spa,
                data  = fs_dat)
summary(tspa_fit)
semPlot::semPaths(tspa_fit)
standardizedSolution(tspa_fit)
standardizedSolution(fit)
```

### Including covariances

```{r}
# Put factor scores to data set
fs_dat <- lavPredict(cfa_fit, acov = "standard")
# Compute reliability (with error covariances)
cfa_psi <- lavInspect(cfa_fit, what = "est")$psi
# Error proportion (i.e., 1 - reliability)
attr(fs_dat, "se")[[1]]^2 / diag(cfa_psi)
# Error correlation
cov2cor(attr(fs_dat, "acov")[[1]])
colnames(fs_dat) <- c("fs_ind60", "fs_dem60")
my2spa <- '
   # latent variables (indicated by factor scores)
     ind60 =~ 1 * fs_ind60
     dem60 =~ 1 * fs_dem60
   # constrain the errors
     fs_ind60 ~~ ev1 * fs_ind60
     fs_dem60 ~~ ev2 * fs_dem60
     fs_ind60 ~~ ecov12 * fs_dem60
   # latent variances
     ind60 ~~ v1 * ind60
     dem60 ~~ v2 * dem60
   # regressions
     dem60 ~ ind60
   # reliability constraints (reliability = v / (v + ev))
   # v = reliability / (1 - reliability) * ev
     ev1 == 0.036168782 / (1 - 0.036168782) * v1
     ev2 == 0.104325961 / (1 - 0.104325961) * v2
     ecov12 == 0.03585019 * sqrt(ev1 * ev2)
'
tspa_fit <- sem(model = my2spa,
                data  = fs_dat)
summary(tspa_fit)
semPlot::semPaths(tspa_fit)
standardizedSolution(tspa_fit)
standardizedSolution(fit)
```

## A three-variable example

```{r}
# CFA
cfa_3var <- '
   # latent variables
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + y2 + y3 + y4
     dem65 =~ y5 + y6 + y7 + y8
   # residual correlations
     y1 ~~ y5
     y2 ~~ y4 + y6
     y3 ~~ y7
     y4 ~~ y8
     y6 ~~ y8
'
cfa_3var_fit <- cfa(model = cfa_3var,
                    data  = PoliticalDemocracy)
semPlot::semPaths(cfa_3var_fit)
# Compute factor scores using lavPredict
lavPredict(cfa_3var_fit, se = "standard")
# reliability of factor scores
# 1 - fx_se^2 / fx_psi
1 - unlist(attributes(lavPredict(cfa_3var_fit, se = "standard"))$se)^2 / 
  parameterestimates(cfa_3var_fit)[23:25, ]$est
rel_ind60 <- 0.9968282
rel_dem60 <- 0.8503460
rel_dem65 <- 0.8430526
```


```{r}
# Put factor scores to data set
fs_3var_dat <- lavPredict(cfa_3var_fit, se = "standard")
colnames(fs_3var_dat) <- c("fs_ind60", "fs_dem60", "fs_dem65")
my2spa_3var <- '
   # latent variables (indicated by factor scores)
     ind60 =~ 1 * fs_ind60
     dem60 =~ 1 * fs_dem60
     dem65 =~ 1 * fs_dem65
   # constrain the errors
     fs_ind60 ~~ ev1 * fs_ind60
     fs_dem60 ~~ ev2 * fs_dem60
     fs_dem65 ~~ ev3 * fs_dem65
   # latent variances
     ind60 ~~ v1 * ind60
     dem60 ~~ v2 * dem60
     dem65 ~~ v3 * dem65
   # regressions
     dem60 ~ ind60
     dem65 ~ ind60 + dem60
   # reliability constraints (reliability = v / (v + ev))
   # v = reliability / (1 - reliability) * ev
     v1 == 0.9968282 / (1 - 0.9968282) * ev1
     v2 == 0.8503460 / (1 - 0.8503460) * ev2
     v3 == 0.8430526 / (1 - 0.8430526) * ev3
'
tspa_3var_fit <- sem(model = my2spa_3var,
                     data  = fs_3var_dat)
summary(tspa_3var_fit)
semPlot::semPaths(tspa_3var_fit)
standardizedSolution(tspa_3var_fit)
```

### Including covariances

```{r}
# Put factor scores to data set
fs_3var_dat <- lavPredict(cfa_3var_fit, acov = "standard")
# Compute reliability (with error covariances)
cfa_3var_psi <- lavInspect(cfa_3var_fit, what = "est")$psi
# Error proportion (i.e., 1 - reliability)
attr(fs_3var_dat, "se")[[1]]^2 / diag(cfa_3var_psi)
# Error correlation
cov2cor(attr(fs_3var_dat, "acov")[[1]])
colnames(fs_3var_dat) <- c("fs_ind60", "fs_dem60", "fs_dem65")
my2spa_3var <- '
   # latent variables (indicated by factor scores)
     ind60 =~ 1 * fs_ind60
     dem60 =~ 1 * fs_dem60
     dem65 =~ 1 * fs_dem65
   # constrain the errors
     fs_ind60 ~~ ev1 * fs_ind60 + ecov12 * fs_dem60 + ecov13 * fs_dem65
     fs_dem60 ~~ ev2 * fs_dem60 + ecov23 * fs_dem65
     fs_dem65 ~~ ev3 * fs_dem65
   # latent variances
     ind60 ~~ v1 * ind60
     dem60 ~~ v2 * dem60
     dem65 ~~ v3 * dem65
   # regressions
     dem60 ~ ind60
     dem65 ~ ind60 + dem60
   # reliability constraints (reliability = v / (v + ev))
   # v = reliability / (1 - reliability) * ev
     ev1 == 0.0358421365 / (1 - 0.0358421365) * v1
     ev2 == 0.0953198255 / (1 - 0.0953198255) * v2
     ev3 == 0.083440568 / (1 - 0.083440568) * v3
     ecov12 == -0.007237295 * sqrt(ev1 * ev2)
     ecov13 == 0.088285662 * sqrt(ev1 * ev3)
     ecov23 == 0.789491689 * sqrt(ev2 * ev3)
'
tspa_3var_fit <- sem(model = my2spa_3var,
                     data  = fs_3var_dat)
summary(tspa_3var_fit)
semPlot::semPaths(tspa_3var_fit)
standardizedSolution(tspa_3var_fit)
```

## Example of Lui (2019)

```{r}
lui2018 <- read_sav("https://osf.io/wxjsg/download") %>%
  filter_at(vars(class14, audit1:audit3), ~ !is.na(.)) %>% 
  filter(eth %in% 1:4) %>%
  mutate_at(vars(class1:class15, audit1:audit10), as.numeric) %>%
  mutate(campuslive = factor(campuslive), 
         eth = factor(eth, 1:4)) %>%
  arrange(eth)
```


[WT]: # (Estimating fx and fy in the same model yields similar results as estimating them in two separate models, although a few parameter estiamtes differ slightly.)

```{r}
# partial scalar model on X, and scalar model on Y
ps_mod <- "
fx =~ class1 + class2 + class3 + class4 + class5 + class6 + 
      class7 + class8 + class9 + class10 + class11 + class12 + 
      class13 + class14 + class15
fy =~ audit1 + audit2 + audit3

class1 ~ c(i1, i1, i1, i1.h)*1
class2 ~ c(i2, i2, i2, i2.h)*1
class4 ~ c(i4.w, i4, i4, i4)*1
class6 ~ c(i6, i6, i6.b, i6)*1
class10 ~ c(i10, i10.a, i10, i10)*1
class11 ~ c(i11, i11, i11, i11.h)*1
class12 ~ c(i12, i12.a, i12, i12)*1
class13 ~ c(i13, i13, i13.b, i13)*1
class14 ~ c(i14.w, i14, i14, i14)*1
class15 ~ c(i15, i15.a, i15, i15)*1
"
```

```{r}
psfit_eth <- cfa(model = ps_mod, 
                 data = lui2018, 
                 group = "eth", 
                 group.label = 1:4, 
                 group.equal = c("loadings", "intercepts"), 
                 std.lv = TRUE)
```

```{r}
# Compute factor scores using lavPredict
lavPredict(psfit_eth, se = "standard")

# Reliability of factor scores (1 - fx_se^2 / fx_psi)
1 - unlist(attributes(lavPredict(psfit_eth, se = "standard"))$se)^2 / 1

# Four groups: white (w), asian (a), black (b), hispanic (h)
rel_fx_w <- 0.9280397
rel_fx_a <- 0.8854708
rel_fx_b <- 0.9241833
rel_fx_h <- 0.9389290
rel_fy_w <- 0.9122641
rel_fy_a <- 0.9108694
rel_fy_b <- 0.9172431
rel_fy_h <- 0.9120363
```

```{r eval=FALSE}
# Put factor scores to data set
fs_lui <- cbind(do.call(rbind, lavPredict(psfit_eth, se = "standard")), 
                    rep(1:4, table(lui2018$eth)))
colnames(fs_lui) <- c("fs_fx", "fs_fy", "eth")
my2spa_lui <- '
   # latent variables (indicated by factor scores)
     fx =~ 1 * fs_fx
     fy =~ 1 * fs_fy
   # constrain the errors
     fs_fx ~~ ev1 * fs_fx
     fs_fy ~~ ev2 * fs_fy
   # latent variances
     fx ~~ v1 * fx
     fy ~~ v2 * fy
   # regressions
     fy ~ b1 * fx
   # reliability constraints (reliability = v / (v + ev))
   # v = reliability / (1 - reliability) * ev
     v1 == c(0.9280397 / (1 - 0.9280397), 
             0.8854708 / (1 - 0.8854708), 
             0.9241833 / (1 - 0.9241833), 
             0.9389290 / (1 - 0.9389290)) * ev1
     v2 == c(0.9122641 / (1 - 0.9122641), 
             0.9108694 / (1 - 0.9108694), 
             0.9172431 / (1 - 0.9172431), 
             0.9120363 / (1 - 0.9120363)) * ev2 - b1^2 * v1
'
# does not work
tspa_lui_fit <- sem(model = my2spa_lui,
                    data  = fs_lui, 
                    group = "eth", 
                    group.label = 1:4, )
summary(tspa_lui_fit)
semPlot::semPaths(tspa_lui_fit)
standardizedSolution(tspa_lui_fit)
```
