---
title: "Structural After Measurement (SAM) Approach and Two-Stage Path Analysis (2S-PA)"
author: "Winnie Wing-Yee Tse"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lavaan)
library(tidyverse)
devtools::load_all()
```

```{r helper-fun}
# creates a comparison table between results from sam and tspa
tab_compare <- function(sam_fit, tspa_fit) {
  sam <- parameterestimates(sam_fit, standardized = TRUE) %>%
    select(lhs, op, rhs, est, se, std.all) %>%
    rename_at(vars(est:std.all), ~ paste0("sam_", .))
  tspa <- parameterestimates(tspa_fit, standardized = TRUE) %>%
    select(lhs, op, rhs, est, se, std.all) %>%
    rename_at(vars(est:std.all), ~ paste0("tspa_", .))
  left_join(sam, tspa, by = c("lhs", "op", "rhs")) %>%
    select(lhs, op, rhs, contains("est"), contains("se"), contains("std.all"))
}
```



## Single group, single predictor

```{r}
model <- ' 
  # latent variable definitions
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + a*y2 + b*y3 + c*y4

  # regressions
    dem60 ~ ind60
'
```

```{r}
# local method
local_sam_fit <- sam(model, data = PoliticalDemocracy, sam.method = "local", 
                     mm.list = list(ind = "ind60", dem = "dem60"))
summary(local_sam_fit)
# global method
global_sam_fit <- sam(model, data = PoliticalDemocracy, sam.method = "global", 
                      mm.list = list(ind = "ind60", dem = "dem60"))
summary(global_sam_fit)
```


```{r}
fs_dat_ind60 <- get_fs(data = PoliticalDemocracy, 
                       model = "ind60 =~ x1 + x2 + x3")
fs_dat_dem60 <- get_fs(data = PoliticalDemocracy, 
                       model = "dem60 =~ y1 + y2 + y3 + y4")
fs_dat <- cbind(fs_dat_ind60, fs_dat_dem60)
tspa_fit <- tspa(model = "dem60 ~ ind60", 
              data = fs_dat, 
              se = list(ind60 = 0.1234937, dem60 = 0.7174736))
summary(tspa_fit)
```


```{r}
tab_compare(local_sam_fit, tspa_fit)
tab_compare(global_sam_fit, tspa_fit)
```

SAM and 2S-PA yielded similar results in the single-group single-predictor example. 


## Single group, multiple predictors

```{r}
model <- ' 
  # latent variable definitions
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + y2 + y3 + y4
     dem65 =~ y5 + y6 + y7 + y8

  # regressions
    dem60 ~ ind60
    dem65 ~ ind60 + dem60

  # # residual correlations
  #   y1 ~~ y5
  #   y2 ~~ y4 + y6
  #   y3 ~~ y7
  #   y4 ~~ y8
  #   y6 ~~ y8
'
```

```{r}
# local method
local_sam_fit <- sam(model, data = PoliticalDemocracy, sam.method = "local", 
                     mm.list = list(ind = "ind60", dem = c("dem60", "dem65")))
summary(local_sam_fit)
# global method
global_sam_fit <- sam(model, data = PoliticalDemocracy, sam.method = "global", 
                      mm.list = list(ind = "ind60", dem = c("dem60", "dem65")))
summary(global_sam_fit)
```

```{r}
fs_dat_ind60 <- get_fs(data = PoliticalDemocracy, 
                       model = "ind60 =~ x1 + x2 + x3")
fs_dat_dem60 <- get_fs(data = PoliticalDemocracy, 
                       model = "dem60 =~ y1 + y2 + y3 + y4")
fs_dat_dem65 <- get_fs(data = PoliticalDemocracy, 
                       model = "dem65 =~ y5 + y6 + y7 + y8")
fs_dat <- cbind(fs_dat_ind60, fs_dat_dem60, fs_dat_dem65)
tspa_3var_fit <- tspa(model = "dem60 ~ ind60
                          dem65 ~ ind60 + dem60", 
                      data = fs_dat, 
                      se = list(ind60 = 0.1234937, dem60 = 0.7174736, 
                                dem65 = 0.6034639))
cat(attributes(tspa_fit)$tspaModel)
```

```{r}
# tab_compare(fit.sam, tspa_fit)
tab_compare(local_sam_fit, tspa_3var_fit)
tab_compare(global_sam_fit, tspa_3var_fit)
```


## Multigroup, single predictor

```{r}
model <- ' 
  # latent variable definitions
    visual =~ x1 + x2 + x3
    speed =~ x7 + x8 + x9

  # regressions
    visual ~ speed
'
```

```{r}
# local method
local_sam_fit <- sam(model, data = HolzingerSwineford1939, 
                     group = "school", sam.method = "local", 
                     group.equal = "regressions")
summary(local_sam_fit)
# global method
global_sam_fit <- sam(model, data = HolzingerSwineford1939, 
                      group = "school", sam.method = "global", 
                      group.equal = "regressions")
summary(global_sam_fit)
```

`sam()` does not follow the equality constrain on the regression coefficients and freely estimates them in each group. 

```{r}
hs_mod <- '
visual =~ x1 + x2 + x3
speed =~ x7 + x8 + x9
'

# get factor scores
fs_dat_visual <- get_fs(data = HolzingerSwineford1939, 
                        model = "visual =~ x1 + x2 + x3", 
                        group = "school")
fs_dat_speed <- get_fs(data = HolzingerSwineford1939, 
                       model = "speed =~ x7 + x8 + x9", 
                        group = "school")
fs_hs <- cbind(fs_dat_visual, fs_dat_speed)

# tspa model
tspa_fit <- tspa(model = "visual ~ speed",
                 data = fs_hs,
                 se = data.frame(visual = c(0.4132437, 0.3729586),
                                 speed = c(0.3424402, 0.3039834)),
                 group = "school"
                 # group.equal = "regressions"
                 )
standardizedsolution(tspa_fit)  %>% filter(op == "~")
```

```{r}
standardizedsolution(local_sam_fit) %>% filter(op == "~")
```


```{r}
tab_compare(local_sam_fit, tspa_fit)
tab_compare(global_sam_fit, tspa_fit)
```



