---
title: "2S-PA with Interaction"
author: "Hok Chio (Mark) Lai"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tspa-interaction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

From https://www.mdpi.com/2624-8611/3/3/24

```{r}
library(lavaan)
library(semTools)
library(R2spa)
library(dplyr)
library(nlsem)
dat <- read.csv("https://osf.io/download/grwn2/")
```

# Unconstrained Product Indicator

```{r}
modME <- '
tvalue =~ t1 + t2 + t3 + t4
sources =~ s1 + s2 + s3 + s4 + s5
tip =~ tip1 + tip2 + tip3


tip ~ tvalue + sources 

'

fitME <- sem(modME, data = dat, std.lv = TRUE, estimator = "mlr")
summary(fitME, fit.measure = TRUE)

## Compute product indicators (double mean centering)

#create names
#not required, but makes syntax easier to write
tvalue <- paste0("t", 1:4)
sources <- paste0("s", 1:5)

intNames <- paste0(rep(tvalue, each = length(sources)), sources)

dat3 <- indProd(dat, var1 = c("t1", "t2", "t3", "t4"),
                var2 = c("s1", "s2", "s3", "s4", "s5"),
                match = FALSE, doubleMC = TRUE,
                namesProd = intNames)

## Mean Centering interaction model

modintMC <- '

tvalue =~ t1 + t2 + t3 + t4
sources =~ s1 + s2 + s3 + s4 + s5
tip =~ tip1 + tip2 + tip3

int =~ t1s1 + t1s2 + t1s3 + t1s4 + t1s5 +        
       t2s1 + t2s2 + t2s3 + t2s4 + t2s5 + 
       t3s1 + t3s2 + t3s3 + t3s4 + t3s5 + 
       t4s1 + t4s2 + t4s3 + t4s4 + t4s5 


tip ~ b1*tvalue + b2*sources + b3*int

#Residual covariances between terms from the same indicator 
#covariances between the same indicator are constrained to equality
t1s1 ~~ th1*t1s2 + th1*t1s3 + th1*t1s4 + th1*t1s5
t1s2 ~~ th1*t1s3 + th1*t1s4 + th1*t1s5
t1s3 ~~ th1*t1s4 + th1*t1s5
t1s4 ~~ th1*t1s5

t2s1 ~~ th2*t2s2 + th2*t2s3 + th2*t2s4 + th2*t2s5
t2s2 ~~ th2*t2s3 + th2*t2s4 + th2*t2s5
t2s3 ~~ th2*t2s4 + th2*t2s5
t2s4 ~~ th2*t2s5

t3s1 ~~ th3*t3s2 + th3*t3s3 + th3*t3s4 + th3*t3s5
t3s2 ~~ th3*t3s3 + th3*t3s4 + th3*t3s5
t3s3 ~~ th3*t3s4 + th3*t3s5
t3s4 ~~ th3*t3s5

t4s1 ~~ th4*t4s2 + th4*t4s3 + th4*t4s4 + th4*t4s5
t4s2 ~~ th4*t4s3 + th4*t4s4 + th4*t4s5
t4s3 ~~ th4*t4s4 + th4*t4s5
t4s4 ~~ th4*t4s5

t1s1 ~~ th5*t2s1 + th5*t3s1 + th5*t4s1 
t2s1 ~~ th5*t3s1 + th5*t4s1 
t3s1 ~~ th5*t4s1 

t1s2 ~~ th6*t2s2 + th6*t3s2 + th6*t4s2 
t2s2 ~~ th6*t3s2 + th6*t4s2 
t3s2 ~~ th6*t4s2 

t1s3 ~~ th7*t2s3 + th7*t3s3 + th7*t4s3 
t2s3 ~~ th7*t3s3 + th7*t4s3 
t3s3 ~~ th7*t4s3 

t1s4 ~~ th8*t2s4 + th8*t3s4 + th8*t4s4 
t2s4 ~~ th8*t3s4 + th8*t4s4 
t3s4 ~~ th8*t4s4 

t1s5 ~~ th9*t2s5 + th9*t3s5 + th9*t4s5 
t2s5 ~~ th9*t3s5 + th9*t4s5 
t3s5 ~~ th9*t4s5 
'

fitintMC <- sem(modintMC, data = dat3, std.lv = TRUE, meanstructure = TRUE)
summary(fitintMC, fit.measure = TRUE, standardized = TRUE)
```

```{r upi function}
# Testing
df <- read.csv("https://osf.io/download/grwn2/")
model <- '
tvalue =~ t1 + t2 + t3 + t4
sources =~ s1 + s2 + s3 + s4 + s5
tip =~ tip1 + tip2 + tip3
tip ~ tvalue + sources + tvalue:sources
'
summary(upi(data = df,
            model = model),
        fit.measure = TRUE,
        standardized = TRUE)
```

# Reliability-adjusted Product Indicator

```{r}
PE <- parameterEstimates(fitintMC)
tvalues <- c("t1", "t2", "t3", "t4")
sources <- c("s1", "s2", "s3", "s4", "s5")
tips <- c("tip1", "tip2", "tip3")

# Sum of factor loadings
tvalues_lambda <- sum(PE[match(tvalues, PE$rhs), "est"])
sources_lambda <- sum(PE[match(sources, PE$rhs), "est"])
tips_lambda <- sum(PE[match(tips, PE$rhs), "est"])

# Sum of error variances and se
PE_vcov <- PE[PE$op == "~~", ]
PE_vcov <- PE_vcov[PE_vcov$label == "", ]
tvalues_error <- sum(PE_vcov[match(tvalues, PE_vcov$rhs), "est"])
sources_error <- sum(PE_vcov[match(sources, PE_vcov$rhs), "est"])
tips_error <- sum(PE_vcov[match(tips, PE_vcov$rhs), "est"])

tvalues_se <- sqrt(tvalues_error)
sources_se <- sqrt(sources_error)
tips_se <- sqrt(tips_error)

# Sum of item scores
dat_sum <- dat %>% 
  mutate(tvalues_sum = rowSums(dat[, tvalues]),
         tsum_centered = tvalues_sum - mean(tvalues_sum, na.rm = T),
         sources_sum = rowSums(dat[, sources]),
         ssum_centered = sources_sum - mean(sources_sum, na.rm = T),
         tips_sum = rowSums(dat[, tips]),
         tips_sum_centered = tips_sum - mean(tips_sum, na.rm = T),
         int = tsum_centered*ssum_centered,
         int_centered = int - mean(int, na.rm = T))

int_var <- tvalues_lambda^2*sources_error + 
  sources_lambda^2*tvalues_error + 
  sources_error*tvalues_error 

sqrt(int_var)

# Single-indicator Model

model_rapi <- "
              tvalue =~ 2.987473*tsum_centered
              sources =~ 3.989224*ssum_centered
              tip =~ 1.328669*tips_sum_centered
              product_ind =~ 2.987473*3.989224*int_centered
              
              # Constrain the errors
              tsum_centered ~~ 1.70026*tsum_centered
              ssum_centered ~~ 3.55476*ssum_centered
              tips_sum_centered ~~ 2.498348*tips_sum_centered
              int_centered ~~ 64.82799*int_centered
              
              # regressions
              tip ~ b1*tvalue + b2*sources + b3*product_ind
              
              #Define Standardized Coefficients
              beta1 := b1 * sqrt(1.70026)
              beta2 := b2 * sqrt(3.55476)
              beta3 := b3 * sqrt(64.82799)
              "

fit_rapi <- sem(model_rapi, 
                data = dat_sum[, c("tsum_centered", "ssum_centered", "tips_sum_centered", "int_centered")],
                std.lv = TRUE,
                meanstructure = TRUE)
summary(fit_rapi, standardized = TRUE)
```

```{r rapi function}
# Testing
df <- read.csv("https://osf.io/download/grwn2/")
model <- '
tvalue =~ t1 + t2 + t3 + t4
sources =~ s1 + s2 + s3 + s4 + s5
tip =~ tip1 + tip2 + tip3
tip ~ tvalue + sources + tvalue:sources
'
summary(rapi(data = df,
            model = model),
        fit.measure = TRUE,
        standardized = TRUE)

lavInspect(rapi(data = df,
            model = model), "cov.lv")
```

# 2S-PA

```{r}
mod_cfa <- '
tvalue =~ t1 + t2 + t3 + t4
sources =~ s1 + s2 + s3 + s4 + s5
tip =~ tip1 + tip2 + tip3
'
# Obtain factor scores
fs_dat <- get_fs(dat, model = mod_cfa, method = "Bartlett", std.lv = TRUE)
```

```{r}
# Obtain factor product
fs_dat$fs_int <- fs_dat$fs_tvalue * fs_dat$fs_sources
# Centering the product variable
fs_dat$fs_int <- fs_dat$fs_int - mean(fs_dat$fs_int)
```

From equation (7) of Hsiao et al. (2018, doi: 10.1177/0013164416679877)

```{r}
fs_dat$fs_int_se <- sqrt(1 * 0.1219141 + 1 * 0.2024207 + 0.1219141 * 0.2024207)
```

```{r}
modinttspa <- '
# latent variables (indicated by factor scores)
tvalue =~ fs_tvalue
sources =~ fs_sources
tip =~ fs_tip
int =~ fs_int

# constrain the errors
fs_tvalue ~~ 0.1219141 * fs_tvalue
fs_sources ~~ 0.2024207 * fs_sources
fs_int ~~ 0.3490127 * fs_int
fs_tip ~~ 0.694483 * fs_tip

# regressions
tip ~ tvalue + sources + int
'
fitinttspa <- sem(modinttspa, data = fs_dat, std.lv = TRUE)
summary(fitinttspa, standardized = TRUE)
```

The model seems working pretty well!

```{r}
fitMC_pars <- parameterEstimates(fitintMC)
fitinttspa_pars <- parameterEstimates(fitinttspa)
``` 

```{r tspa function with interaction}
mod_cfa <- '
tvalue =~ t1 + t2 + t3 + t4
sources =~ s1 + s2 + s3 + s4 + s5
tip =~ tip1 + tip2 + tip3
'
# Obtain factor scores
fs_dat <- get_fs(dat, model = mod_cfa, method = "Bartlett", std.lv = TRUE)

fit <- tspa(model = "tip ~ tvalue + sources + tvalue:sources",
             data = fs_dat,
             se = list(tvalue = 0.349162, sources =  0.4499119,
                       tip = 0.8333564))

summary(fit, standardized = TRUE)
cat(attributes(fit)$tspaModel)
```

# Using factor scores without contraining measurement errors

```{r}
mod_cfa <- '
tvalue =~ t1 + t2 + t3 + t4
sources =~ s1 + s2 + s3 + s4 + s5
tip =~ tip1 + tip2 + tip3
'
# Obtain factor scores
fs_dat <- get_fs(dat, model = mod_cfa, method = "Bartlett", std.lv = TRUE)

# Obtain factor product
fs_dat$fs_int <- fs_dat$fs_tvalue * fs_dat$fs_sources
# Centering the product variable
fs_dat$fs_int <- fs_dat$fs_int - mean(fs_dat$fs_int)

modinttspa <- '
# latent variables (indicated by factor scores)
tvalue =~ fs_tvalue
sources =~ fs_sources
tip =~ fs_tip
int =~ fs_int

# regressions
tip ~ tvalue + sources + int
'
fitinttspa <- sem(modinttspa, data = fs_dat)
summary(fitinttspa, standardized = TRUE)
```

# Latent Moderated Structural Equations (LMS)

```{r}
lms <- specify_sem(num.x = 9, num.y = 3, num.xi = 2, num.eta = 1, xi = "x1-x4,x5-x9",
  eta = "y1-y3", interaction = "xi1:xi2")

start <- runif(count_free_parameters(lms))

dat_lms <- dat %>% 
  slice(1:1000) %>%
  select(-X) %>%
  na.omit()

colnames(dat_lms) <- c(paste0(rep("x", 9), 1:9), paste0(rep("y", 3), 1:3))

res_lms <- em(lms, dat_lms, start, convergence = 0.1)
summary(res_lms)
plot(res_lms)
```





